### ISSUE TITLE
[Feuture Request] Android build

### ISSUE THREAD

**Issue by xTMODx** [j-selby/ThePowderToy-LibRetro#1]
I would like to see the android build here if possible. Here the information i found so far.
https://github.com/jacob1/The-Powder-Toy/blob/c%2B%2B/COMPILING
https://gist.github.com/jacob1/7556fd14c3589818c4d2
http://powdertoy.co.uk/Discussions/Thread/View.html?Thread=20392

**Comment by j-selby** [comment]
The documentation that you provided isn't particularly useful here, as we have changed all of the build systems for the LibRetro port. That said, the core should already work as-is on Android - have you tried compiling it for that platform?

**Comment by xTMODx** [comment]
Sorry i am not expirienced with compiling. Maybe @fr500 can test it?

**Comment by xTMODx** [comment]
The core is starting on my phone but crash after a few seconds... at least this issue can be closed.

**Comment by j-selby** [comment]
What specs are your device?

**Comment by xTMODx** [comment]
My phone is Galaxy Note 8 with the qualcomm 835 chipset... the standalone works fine, i just did a test with newest core and it still crash after a few seconds

**Comment by j-selby** [comment]
Could you please open a new issue about the bug, with a crash log? Thanks!
